name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean verify -P coverage --no-transfer-progress --file pom.xml
      - uses: codecov/codecov-action@v2
        with:
          files: apt/target/site/jacoco/jacoco.xml,impl/target/site/jacoco/jacoco.xml
